-- H2-friendly schema (local)

create table "user"(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
  email varchar(255) not null unique,
  username varchar(64) not null unique,
  password_hash varchar(255) not null,
  email_verified boolean not null default false,
  created_at TIMESTAMP not null default CURRENT_TIMESTAMP
);

-- project
create table project(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
  "owner_id" bigint not null,
  name varchar(200) not null,
  description text,
  tex_key varchar(1024),
  pdf_key varchar(1024),
  artifact_version int default 0,
  status varchar(16) not null default 'draft',
  created_at TIMESTAMP not null default CURRENT_TIMESTAMP,
  updated_at TIMESTAMP not null default CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  constraint fk_project_owner foreign key ("owner_id") references "user"(id)
);

-- project_page
create table project_page(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
  "project_id" bigint not null,
  page_index int not null,
  source_image_key varchar(1024) not null,
  thumb_key varchar(1024),
  ocr_json_key varchar(1024),
  latex text,
  status varchar(16) not null default 'uploaded',
  width int,
  height int,
  checksum varchar(128),
  created_at TIMESTAMP not null default CURRENT_TIMESTAMP,
  constraint fk_page_project foreign key ("project_id") references project(id),
  constraint uq_project_page unique ("project_id", page_index)
);

create index idx_project_page_index on project_page("project_id", page_index);