-- verification_token
drop table if exists verification_token;

create table verification_token (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
  token varchar(255) not null unique,
  "user_id" bigint not null,
  expires_at TIMESTAMP not null,
  used boolean not null default false,
  constraint fk_verification_token_user
    foreign key ("user_id") references "user"(id)
);

create index idx_verification_token_user on verification_token("user_id");

-- password_reset_token
drop table if exists password_reset_token;

create table password_reset_token (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
  token varchar(255) not null unique,
  "user_id" bigint not null,
  expires_at TIMESTAMP not null,
  used boolean not null default false,
  constraint fk_password_reset_token_user
    foreign key ("user_id") references "user"(id)
);

create index idx_password_reset_token_user on password_reset_token("user_id");
