server:
  address: 0.0.0.0
  port: 8080

app:
  backend-public-base-url: http://192.168.50.68:8080
  frontend:
    verify-redirect: app://auth/verify
    reset-redirect: app://auth/reset-ok

spring:
  datasource:
    url: jdbc:h2:mem:ntx;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: validate
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
  h2.console.enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}         # полный адрес
    password: ${SPRING_MAIL_PASSWORD}     # 16-символьный app password из Google
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
        debug: true

rabbitmq:
  host: localhost
  port: 5672

note2tex:
  s3:
    endpoint: http://localhost:9000
    accessKey: minio
    secretKey: minio123
